# Generated by Django 5.0.4 on 2024-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_newuser_first_name_newuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
