# Generated by Django 5.0.4 on 2024-05-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_newuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
