# Generated by Django 5.0.4 on 2024-05-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_newuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
