# Generated by Django 5.0.4 on 2024-05-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_newuser_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
